---
instituicao: Centro Universitário de João Pessoa
author: ""
title: Alagômetro - Um sistema distribuído de detecção e notificação de alagamentos
local: João Pessoa - PB
date: '2020'
capa_pdf_caminho: ''
titulacao: Minha-titulação
curso: Graduação em Engenharia Elétrica
programa: ''
departamento: Departamento de Engenharia Civil, Mecânica e Elétrica
area_de_concentracao: false
linha_de_pesquisa: ''
coorientador: ''
orientador: 
referencias_caminho: referencias.bib
proposito: ''
resumo: ''
palavras_chave: ''
keywords: ''
abstract_texto: ''
resumen: ''
palabras_clave: ''
resume: ''
mots_cles: ''
simbolos: 
dedicatoria: ''
agradecimentos: ''
epigrafe: ''
avaliador2: Nome-do-Prof-Convidado2
aprovacao_dia: '1'
avaliador1: Nome-do-Prof-Convidado1
avaliador3: ''
disciplina: 'Física Aplicada I'
relatorio: false
projeto_integrador: true
graduacao: false
especializacao: false
mestrado: false
doutorado: false
tipo_do_trabalho: Projeto Integrador
incluir_ficha_catalografica: false
folha_de_aprovacao: false
projeto: true
apendices: false
anexos: false
errata: false
referencias_sistema: alf
lista_ilustracoes: false
lista_quadros: false
lista_tabelas: false

---
